new new

diff --git a/.github/workflows/building_blogs.yaml b/.github/workflows/building_blogs.yaml
--- a/.github/workflows/building_blogs.yaml
+++ b/.github/workflows/building_blogs.yaml
@@ -2,19 +2,20 @@ name: Building Blocks
 
 on: push
 
-jobs: 
+jobs:
     echo-hello:
         runs-on: ubuntu-latest
         steps:
             - name: Say hello
-              run: echo "Hello, World!"
+              run: echo "hello,World!"
 
     echo-goodbye:
         runs-on: ubuntu-latest
         steps:
-                - name: Failed step
-                  run: 
-                    echo "This step will fail"
-                    exit 1
-                - name: Say goodbye
-                  run: echo "Goodbye, World!"
+            - name: Failed step
+              run: |
+                echo "This step will fail"
+                exit 1
+            - name: Say goodbye
+              if: always()
+              run: echo "goodbye,World!"
